// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package dbgen

import (
	"context"
	"time"
)

const createFeedIfNotExists = `-- name: CreateFeedIfNotExists :exec
INSERT OR IGNORE INTO rss_feeds (url, created_at) VALUES (?, ?)
`

type CreateFeedIfNotExistsParams struct {
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFeedIfNotExists(ctx context.Context, arg CreateFeedIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, createFeedIfNotExists, arg.Url, arg.CreatedAt)
	return err
}

const getAllFeeds = `-- name: GetAllFeeds :many
SELECT url, title, content, last_fetched, last_error, created_at FROM rss_feeds ORDER BY url
`

func (q *Queries) GetAllFeeds(ctx context.Context) ([]RssFeed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RssFeed{}
	for rows.Next() {
		var i RssFeed
		if err := rows.Scan(
			&i.Url,
			&i.Title,
			&i.Content,
			&i.LastFetched,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT url, title, content, last_fetched, last_error, created_at FROM rss_feeds WHERE url = ?
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i RssFeed
	err := row.Scan(
		&i.Url,
		&i.Title,
		&i.Content,
		&i.LastFetched,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getStaleFeeds = `-- name: GetStaleFeeds :many
SELECT url, title, content, last_fetched, last_error, created_at FROM rss_feeds WHERE last_fetched IS NULL OR last_fetched < ? ORDER BY last_fetched
`

func (q *Queries) GetStaleFeeds(ctx context.Context, lastFetched *time.Time) ([]RssFeed, error) {
	rows, err := q.db.QueryContext(ctx, getStaleFeeds, lastFetched)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RssFeed{}
	for rows.Next() {
		var i RssFeed
		if err := rows.Scan(
			&i.Url,
			&i.Title,
			&i.Content,
			&i.LastFetched,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeed = `-- name: UpsertFeed :exec
INSERT INTO rss_feeds (url, title, content, last_fetched, last_error, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(url) DO UPDATE SET
    title = excluded.title,
    content = excluded.content,
    last_fetched = excluded.last_fetched,
    last_error = excluded.last_error
`

type UpsertFeedParams struct {
	Url         string     `json:"url"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	LastFetched *time.Time `json:"last_fetched"`
	LastError   *string    `json:"last_error"`
	CreatedAt   time.Time  `json:"created_at"`
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeed,
		arg.Url,
		arg.Title,
		arg.Content,
		arg.LastFetched,
		arg.LastError,
		arg.CreatedAt,
	)
	return err
}
