// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package dbgen

import (
	"context"
	"time"
)

const checkSlugExists = `-- name: CheckSlugExists :one
SELECT COUNT(*) FROM pages WHERE slug = ? AND id != ?
`

type CheckSlugExistsParams struct {
	Slug *string `json:"slug"`
	ID   string  `json:"id"`
}

func (q *Queries) CheckSlugExists(ctx context.Context, arg CheckSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSlugExists, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :exec
INSERT INTO pages (id, user_id, name, bg_color, bg_image, config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePageParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	BgColor   *string   `json:"bg_color"`
	BgImage   *string   `json:"bg_image"`
	Config    string    `json:"config"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.BgColor,
		arg.BgImage,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = ?
`

func (q *Queries) DeletePage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, user_id, name, bg_color, bg_image, created_at, updated_at, config, slug, is_public, slug_access FROM pages WHERE id = ?
`

func (q *Queries) GetPageByID(ctx context.Context, id string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BgColor,
		&i.BgImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Config,
		&i.Slug,
		&i.IsPublic,
		&i.SlugAccess,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, user_id, name, bg_color, bg_image, created_at, updated_at, config, slug, is_public, slug_access FROM pages WHERE slug = ?
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug *string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BgColor,
		&i.BgImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Config,
		&i.Slug,
		&i.IsPublic,
		&i.SlugAccess,
	)
	return i, err
}

const getPagesByUserID = `-- name: GetPagesByUserID :many
SELECT id, user_id, name, bg_color, bg_image, created_at, updated_at, config, slug, is_public, slug_access FROM pages WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) GetPagesByUserID(ctx context.Context, userID string) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, getPagesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BgColor,
			&i.BgImage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Config,
			&i.Slug,
			&i.IsPublic,
			&i.SlugAccess,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages SET name = ?, bg_color = ?, bg_image = ?, config = ?, updated_at = ? WHERE id = ?
`

type UpdatePageParams struct {
	Name      string    `json:"name"`
	BgColor   *string   `json:"bg_color"`
	BgImage   *string   `json:"bg_image"`
	Config    string    `json:"config"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage,
		arg.Name,
		arg.BgColor,
		arg.BgImage,
		arg.Config,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updatePagePublic = `-- name: UpdatePagePublic :exec
UPDATE pages SET is_public = ?, updated_at = ? WHERE id = ?
`

type UpdatePagePublicParams struct {
	IsPublic  *int64    `json:"is_public"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePagePublic(ctx context.Context, arg UpdatePagePublicParams) error {
	_, err := q.db.ExecContext(ctx, updatePagePublic, arg.IsPublic, arg.UpdatedAt, arg.ID)
	return err
}

const updatePageSlug = `-- name: UpdatePageSlug :exec
UPDATE pages SET slug = ?, updated_at = ? WHERE id = ?
`

type UpdatePageSlugParams struct {
	Slug      *string   `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePageSlug(ctx context.Context, arg UpdatePageSlugParams) error {
	_, err := q.db.ExecContext(ctx, updatePageSlug, arg.Slug, arg.UpdatedAt, arg.ID)
	return err
}

const updatePageSlugAccess = `-- name: UpdatePageSlugAccess :exec
UPDATE pages SET slug_access = ?, updated_at = ? WHERE id = ?
`

type UpdatePageSlugAccessParams struct {
	SlugAccess *int64    `json:"slug_access"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         string    `json:"id"`
}

func (q *Queries) UpdatePageSlugAccess(ctx context.Context, arg UpdatePageSlugAccessParams) error {
	_, err := q.db.ExecContext(ctx, updatePageSlugAccess, arg.SlugAccess, arg.UpdatedAt, arg.ID)
	return err
}
