// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, created_at, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, name, picture, created_at, last_login)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Picture   *string   `json:"picture"`
	CreatedAt time.Time `json:"created_at"`
	LastLogin time.Time `json:"last_login"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.CreatedAt,
		arg.LastLogin,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.created_at, s.expires_at, u.email, u.name as user_name, u.picture 
FROM sessions s 
JOIN users u ON s.user_id = u.id 
WHERE s.id = ? AND s.expires_at > CURRENT_TIMESTAMP
`

type GetSessionRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Email     string    `json:"email"`
	UserName  string    `json:"user_name"`
	Picture   *string   `json:"picture"`
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.UserName,
		&i.Picture,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, picture, created_at, last_login, exedev_id FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.LastLogin,
		&i.ExedevID,
	)
	return i, err
}

const getUserByExedevID = `-- name: GetUserByExedevID :one
SELECT id, email, name, picture, created_at, last_login, exedev_id FROM users WHERE exedev_id = ?
`

func (q *Queries) GetUserByExedevID(ctx context.Context, exedevID *string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExedevID, exedevID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.LastLogin,
		&i.ExedevID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, picture, created_at, last_login, exedev_id FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.LastLogin,
		&i.ExedevID,
	)
	return i, err
}

const linkExedevID = `-- name: LinkExedevID :exec
UPDATE users SET exedev_id = ? WHERE id = ?
`

type LinkExedevIDParams struct {
	ExedevID *string `json:"exedev_id"`
	ID       string  `json:"id"`
}

func (q *Queries) LinkExedevID(ctx context.Context, arg LinkExedevIDParams) error {
	_, err := q.db.ExecContext(ctx, linkExedevID, arg.ExedevID, arg.ID)
	return err
}

const updatePagesOwnership = `-- name: UpdatePagesOwnership :exec
UPDATE pages SET user_id = ? WHERE user_id = ?
`

type UpdatePagesOwnershipParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

func (q *Queries) UpdatePagesOwnership(ctx context.Context, arg UpdatePagesOwnershipParams) error {
	_, err := q.db.ExecContext(ctx, updatePagesOwnership, arg.UserID, arg.UserID_2)
	return err
}

const updateUserLogin = `-- name: UpdateUserLogin :exec
UPDATE users SET name = ?, picture = ?, last_login = ? WHERE id = ?
`

type UpdateUserLoginParams struct {
	Name      string    `json:"name"`
	Picture   *string   `json:"picture"`
	LastLogin time.Time `json:"last_login"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateUserLogin(ctx context.Context, arg UpdateUserLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLogin,
		arg.Name,
		arg.Picture,
		arg.LastLogin,
		arg.ID,
	)
	return err
}
